name: Test Source

# 触发条件：每小时执行一次
on:
  workflow_dispatch:      # 手动触发

jobs:
  update-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch content from cucast URL # 北京联通组播
        run: |
          curl -o cucast_source.txt https://m3u.ibert.me/txt/q_bj_iptv_unicom_m.txt
          touch cucast.txt
          cp cucast_source.txt cucast.txt
          
      - name: Update timestamp in test_time.txt # 测试时间
        run: |
          current_time=$(date "+%Y-%m-%d %H:%M:%S")
          echo "Last update: $current_time" > test_time.txt  # 写入最新时间到文件
          
      - name: Commit and push changes
        run: |
          git config --global user.email "137753051@qq.com"
          git config --global user.name "Sherwood1"
          git add cucast.txt test_time.txt
          git commit -m "Auto update multiple files with webpage contents"
          git push
