name: Test Source

# 触发条件：每小时执行一次
on:
  workflow_dispatch:      # 手动触发

jobs:
  update-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch content from test URL # 测试源
        run: |
          curl -o test_source.txt https://mtt.xwqin.com/api/m3u-txt.php?url=https://raw.githubusercontent.com/fanmingming/live/refs/heads/main/tv/m3u/ipv6.m3u
          touch test.txt
          cp test_source.txt test.txt
          
      - name: Update timestamp in test_time.txt # 测试时间
        run: |
          current_time=$(date "+%Y-%m-%d %H:%M:%S")
          echo "Last update: $current_time" > test_time.txt  # 写入最新时间到文件
          
      - name: Commit and push changes
        run: |
          git config --global user.email "137753051@qq.com"
          git config --global user.name "Sherwood1"
          git add test.txt test_time.txt
          git commit -m "Auto update multiple files with webpage contents"
          git push
